name: 批量保活进程

on:
  schedule:
    - cron: '3 22 * * *' #北京时间6点
  workflow_dispatch:

jobs:
  serv00-tip:
    runs-on: ubuntu-latest
    steps:
      - name: Set up and install dependencies
        run: |
          echo "开始设置和安装依赖包..."
          sudo apt-get update
          sudo apt-get install -y sshpass jq
          echo "依赖包安装完成。"

      - name: Run serv00 tip
        run: |
          echo "开始运行主任务..."
          cat /home/runner/work/_temp/*.sh
          echo ${{ secrets.HOSTS_JSON }} | jq -c '.info[]'

      - name: Send email with attachments
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAILADDR }}
          server_port: ${{ secrets.MAILPORT }}
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: 创建 serv00 提示信息
          to: ${{ secrets.MAILSENDTO }}
          from: GitHub Actions
          body: run job of ${{ github.repository }} completed successfully!
          attachments: result.txt

      - name: Run rm -frv result.txt
        run: rm -frv result.txt
