name: 批量保活进程

on:
  schedule:
    - cron: '3 22 * * *' #北京时间6点
  workflow_dispatch:

jobs:
  serv00-tip:
    runs-on: ubuntu-latest
    steps:
      - name: Set up and install dependencies
        run: |
          echo "开始设置和安装依赖包..."
          sudo apt-get update
          sudo apt-get install -y sshpass jq
          echo "依赖包安装完成。"

      - name: Run serv00 tip
        run: |
          cat << '20241204' | tee ./20241204.sh
          echo "开始运行主任务..."
          echo "${{ secrets.HOSTS_JSON }}"
          # 使用 jq 提取 JSON 数组，并将其加载为 Bash 数组
          hosts_info=($(echo "${{ secrets.HOSTS_JSON }}" | jq -c ".info[]"))
          for info in "${hosts_info[@]}"; do
            echo "处理主机信息: $info"
            user=$(echo $info | jq -r ".username")
            host=$(echo $info | jq -r ".host")
            port=$(echo $info | jq -r ".port")
            pass=$(echo $info | jq -r ".password")
            echo "$user"
            echo "$host"
            echo "$port"
            echo "$pass"
          done
          20241204
          chmod -v a+x ./20241204.sh
          ./20241204.sh
          rm -frv ./20241204.sh

      - name: Send email with attachments
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAILADDR }}
          server_port: ${{ secrets.MAILPORT }}
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: 创建 serv00 提示信息
          to: ${{ secrets.MAILSENDTO }}
          from: GitHub Actions
          body: run job of ${{ github.repository }} completed successfully!
          attachments: result.txt

      - name: Run rm -frv result.txt
        run: rm -frv result.txt
